use super::{Rule, RuleKind, RuleSet, Severity};

pub fn default_ruleset() -> RuleSet {
    RuleSet {
        rules: vec![
            // ========== OBFUSCATION DETECTION ==========
            Rule {
                id: "OBF-001".into(),
                name: "eval usage".into(),
                description: "Direct eval() call — commonly used to execute obfuscated code".into(),
                severity: Severity::High,
                kind: RuleKind::CallExpression,
                pattern: "eval".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-002".into(),
                name: "Function constructor".into(),
                description: "new Function() — dynamic code generation, often obfuscated".into(),
                severity: Severity::High,
                kind: RuleKind::AstNodeType,
                pattern: "new_expression:Function".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-003".into(),
                name: "Hex escape sequences".into(),
                description: "String with hex escapes (\\x..) — used to hide readable strings".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:\\x[0-9a-fA-F]{2}){4,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-004".into(),
                name: "Unicode escape sequences".into(),
                description: "Dense unicode escapes (\\u....) — used to hide identifiers".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:\\u[0-9a-fA-F]{4}){3,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-005".into(),
                name: "Base64 decode call".into(),
                description: "atob() or Buffer.from(..., 'base64') — decoding hidden payloads".into(),
                severity: Severity::Medium,
                kind: RuleKind::CallExpression,
                pattern: "atob".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-006".into(),
                name: "High-entropy string".into(),
                description: "String literal with unusually high entropy — likely encoded payload".into(),
                severity: Severity::Medium,
                kind: RuleKind::Entropy,
                pattern: String::new(),
                pattern2: None,
                threshold: Some(5.0),
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-007".into(),
                name: "Abnormally long line".into(),
                description: "Single line exceeding threshold — packed/minified obfuscation".into(),
                severity: Severity::Low,
                kind: RuleKind::LongLine,
                pattern: String::new(),
                pattern2: None,
                threshold: Some(1000.0),
                tags: vec!["obfuscation".into(), "structure".into()],
            },
            // ========== SUPPLY CHAIN ATTACK PATTERNS ==========
            Rule {
                id: "SC-001".into(),
                name: "process.env access (dot)".into(),
                description: "Reading environment variables — may exfiltrate secrets".into(),
                severity: Severity::Low,
                kind: RuleKind::MemberExpression,
                pattern: "process.env".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-001b".into(),
                name: "process.env access (bracket)".into(),
                description: "Bracket-notation env access — may bypass dot-notation scanners".into(),
                severity: Severity::Low,
                kind: RuleKind::SubscriptExpression,
                pattern: "process.env".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-002".into(),
                name: "child_process require".into(),
                description: "Requiring child_process — can execute arbitrary system commands".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"require\s*\(\s*['"`]child_process['"`]\s*\)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-002b".into(),
                name: "child_process import".into(),
                description: "ESM import of child_process — can execute arbitrary system commands".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"import\s+.*\s+from\s+['"`]child_process['"`]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-003".into(),
                name: "Network exfiltration".into(),
                description: "HTTP request combined with sensitive data access — potential exfiltration".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:fetch\s*\(|https?\.\s*(?:request|get|post)\s*\(|axios\s*[\.\(]|\.post\s*\(|\.put\s*\(|got\s*[\.\(]|node-fetch|request\s*\()".into(),
                pattern2: Some(r"(?:process\.env|secret|token|password|passwd|credential|api[_-]?key|hostname|whoami|userInfo|\.ssh)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-004".into(),
                name: "Dynamic require".into(),
                description: "Dynamic module loading with string construction — can pull in attacker-controlled code".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"require\s*\(\s*(?:[^'"`\s)]*\+|Buffer\.|atob|decodeURI|String\.fromCharCode|_0x)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-004b".into(),
                name: "Dynamic import()".into(),
                description: "ESM dynamic import() with non-literal argument".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"import\s*\(\s*[^'"`\s]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-006".into(),
                name: "Encoded URL or IP".into(),
                description: "Obfuscated network address — hiding C2 or exfil destination".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"atob\s*\(\s*['\x22][A-Za-z0-9+/=]{20,}['\x22]\s*\)".into(),
                pattern2: Some(r"(?:fetch|https?|request|url|\.get|\.post|connect|socket)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into()],
            },
            Rule {
                id: "SC-007".into(),
                name: "File system read".into(),
                description: "Reading files — may access SSH keys, credentials, or configs".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:readFileSync|readFile|createReadStream|openSync|open\b)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "filesystem".into()],
            },
            Rule {
                id: "SC-008".into(),
                name: "VM execution context".into(),
                description: "vm.runInNewContext/runInThisContext — sandbox escape risk".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"vm\s*\.\s*(?:runInNewContext|runInThisContext|createContext|Script)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-009".into(),
                name: "WebAssembly instantiation".into(),
                description: "WebAssembly.instantiate — can run pre-compiled binary code".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"WebAssembly\s*\.\s*(?:instantiate|compile|instantiateStreaming)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-010".into(),
                name: "Prototype pollution".into(),
                description: "__proto__ or constructor.prototype access — prototype pollution vector".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:__proto__\s*[=\[]|constructor\s*\.\s*prototype\s*[=\.]|\[\s*['\x22`]__proto__['\x22`]\s*\]\s*=)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "prototype-pollution".into()],
            },
            Rule {
                id: "SC-011".into(),
                name: "Sensitive file path".into(),
                description: "Reference to sensitive file path — SSH keys, npmrc, credentials".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:\.ssh/id_rsa|\.ssh/id_ed25519|\.ssh/id_ecdsa|\.ssh/known_hosts|\.ssh/authorized_keys|/\.npmrc|/\.netrc|\.aws/credentials|\.aws/config|\.gnupg/|/etc/passwd|/etc/shadow|\.docker/config\.json|\.kube/config)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-012".into(),
                name: "DNS exfiltration".into(),
                description: "DNS resolution with sensitive data — DNS-based data exfiltration".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:dns\s*\.\s*(?:resolve|lookup)|dgram\s*\.\s*createSocket)\s*\(".into(),
                pattern2: Some(r"(?:process\.env|secret|token|password|credential|api[_-]?key|\.env\b|exfil)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-013".into(),
                name: "Crypto decipher".into(),
                description: "crypto.createDecipher — may decrypt embedded malicious payload (event-stream pattern)".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:createDecipher|createDecipheriv)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "crypto".into()],
            },
            Rule {
                id: "SC-014".into(),
                name: "Indirect eval via global".into(),
                description: "Accessing eval through globalThis/window/global — bypasses direct eval detection".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"(?:globalThis|window|global|self)\s*\[\s*['"`]eval['"`]\s*\]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            // ========== NEW: Expanded coverage ==========
            Rule {
                id: "SC-015".into(),
                name: "Shell command execution".into(),
                description: "execSync/spawn call with suspicious context — arbitrary command execution".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:execSync|execFileSync|spawnSync)\s*\(".into(),
                pattern2: Some(r"(?:curl|wget|bash|sh\b|powershell|cmd\.exe|eval|base64|atob|\\x[0-9a-fA-F]|_0x|fetch|https?://|whoami|hostname|passwd|cat\s+/etc|\.ssh|id_rsa|netstat|ifconfig|ipconfig)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-015b".into(),
                name: "child_process.exec call".into(),
                description: "child_process.exec() — arbitrary command execution".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"child_process['\x22`\]]*\s*[\.\)]\s*exec\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-016".into(),
                name: "Raw network socket".into(),
                description: "net.Socket/createConnection — reverse shell or raw exfiltration channel".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:net\s*\.\s*(?:Socket|createConnection|connect)|new\s+net\s*\.\s*Socket|dgram\s*\.\s*createSocket)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "network".into()],
            },
            Rule {
                id: "SC-017".into(),
                name: "process.mainModule access".into(),
                description: "process.mainModule.require — sandbox escape to load arbitrary modules".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"process\s*\.\s*mainModule\s*\.\s*require\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-018".into(),
                name: "OS fingerprinting".into(),
                description: "os module used for host reconnaissance — platform, user, hostname".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"os\s*\.\s*(?:platform|hostname|userInfo|homedir|networkInterfaces|cpus|release|type)\s*\(".into(),
                pattern2: Some(r"(?:fetch|https?|request|\.post|\.get|send|exfil|dns|socket|process\.env)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "recon".into()],
            },
            Rule {
                id: "SC-019".into(),
                name: "Node.js internal binding".into(),
                description: "process.binding — access dangerous internal modules".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"process\s*\.\s*(?:binding|_linkedBinding)\s*\(\s*['\x22](?:spawn_sync|fs|tcp_wrap|pipe_wrap|udp_wrap|tls_wrap|crypto|child_process)['\x22]".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-020".into(),
                name: "File system write".into(),
                description: "Writing files — payload drop, crontab modification, or key injection".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:writeFileSync|writeFile|appendFileSync|appendFile|createWriteStream)\s*\(".into(),
                pattern2: Some(r"(?:\.ssh|cron|\.bashrc|\.bash_profile|\.profile|authorized_keys|bin/|\.npmrc|payload|backdoor|\.env|passwd|shadow)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "filesystem".into()],
            },
            Rule {
                id: "SC-021".into(),
                name: "Shell command string".into(),
                description: "String containing shell download/execute commands — malware dropper pattern".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"['"`](?:[^'"`]*(?:sudo\s|wget\s|curl\s|chmod\s\+x|/dev/null|sh\s+-c|bash\s+-c|&&\s*\./)[^'"`]*)['"`]"#.into(),
                pattern2: Some(r"(?:https?://|child_process|exec|spawn|Function)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-022".into(),
                name: "child_process member access".into(),
                description: "Accessing exec/spawn methods from child_process — command execution setup".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"require\s*\(\s*['\x22`]child_process['\x22`]\s*\)\s*\.\s*(?:exec|execSync|execFile|execFileSync|spawn|spawnSync|fork)\b".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            // ========== Evasion-resistant patterns ==========
            Rule {
                id: "OBF-008".into(),
                name: "Function constructor reference".into(),
                description: "Function constructor stored in variable/array — indirect dynamic code execution".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:[\[,=]\s*Function\s*[,\];\s]|\bFunction\b\s*(?:,|\]))".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-009".into(),
                name: "String fragment array".into(),
                description: "Array of many short string fragments — hiding URLs, code, or identifiers".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r#"\[\s*"[^"]{1,8}"\s*(?:,\s*"[^"]{1,8}"\s*){5,}\]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-010".into(),
                name: "Bracket-notation method call".into(),
                description: "obj[variable](...) — hiding method name via computed property access".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"\w+\[\s*\w+\s*\]\s*\([^)]*\)\s*\(".into(),
                pattern2: Some(r"(?:Function|eval|require|concat|exec|child_process)".into()),
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
        ],
    }
}
