use super::{Rule, RuleKind, RuleSet, Severity};

pub fn default_ruleset() -> RuleSet {
    RuleSet {
        rules: vec![
            // ========== OBFUSCATION DETECTION ==========
            Rule {
                id: "OBF-001".into(),
                name: "eval usage".into(),
                description: "Direct eval() call — commonly used to execute obfuscated code".into(),
                severity: Severity::High,
                kind: RuleKind::CallExpression,
                pattern: "eval".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-002".into(),
                name: "Function constructor".into(),
                description: "new Function() — dynamic code generation, often obfuscated".into(),
                severity: Severity::Medium,
                kind: RuleKind::AstNodeType,
                pattern: "new_expression:Function".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-003".into(),
                name: "Hex escape sequences".into(),
                description: "String with hex escapes (\\x..) — used to hide readable strings".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:\\x[0-9a-fA-F]{2}){4,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-004".into(),
                name: "Unicode escape sequences".into(),
                description: "Dense unicode escapes (\\u....) — used to hide identifiers".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:\\u[0-9a-fA-F]{4}){3,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-005".into(),
                name: "Base64 decode call".into(),
                description: "atob() or Buffer.from(..., 'base64') — decoding hidden payloads".into(),
                severity: Severity::Medium,
                kind: RuleKind::CallExpression,
                pattern: "atob".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-006".into(),
                name: "High-entropy string".into(),
                description: "String literal with unusually high entropy — likely encoded payload".into(),
                severity: Severity::Low,
                kind: RuleKind::Entropy,
                pattern: String::new(),
                pattern2: None,
                threshold: Some(5.0),
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-007".into(),
                name: "Abnormally long line".into(),
                description: "Single line exceeding threshold — packed/minified obfuscation".into(),
                severity: Severity::Low,
                kind: RuleKind::LongLine,
                pattern: String::new(),
                pattern2: None,
                threshold: Some(1000.0),
                tags: vec!["obfuscation".into(), "structure".into()],
            },
            // ========== SUPPLY CHAIN ATTACK PATTERNS ==========
            Rule {
                id: "SC-001".into(),
                name: "process.env access (dot)".into(),
                description: "Reading environment variables — may exfiltrate secrets".into(),
                severity: Severity::Low,
                kind: RuleKind::MemberExpression,
                pattern: "process.env".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-001b".into(),
                name: "process.env access (bracket)".into(),
                description: "Bracket-notation env access — may bypass dot-notation scanners".into(),
                severity: Severity::Low,
                kind: RuleKind::SubscriptExpression,
                pattern: "process.env".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-002".into(),
                name: "child_process require".into(),
                description: "Requiring child_process — can execute arbitrary system commands".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r#"require\s*\(\s*['"`]child_process['"`]\s*\)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-002b".into(),
                name: "child_process import".into(),
                description: "ESM import of child_process — can execute arbitrary system commands".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r#"import\s+.*\s+from\s+['"`]child_process['"`]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-003".into(),
                name: "Network exfiltration".into(),
                description: "HTTP request combined with sensitive data access — potential exfiltration".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:fetch\s*\(|https?\.\s*(?:request|get|post)\s*\(|axios\s*[\.\(]|\.post\s*\(|\.put\s*\(|got\s*[\.\(]|node-fetch|request\s*\(|undici\s*[\.\(]|http2\s*\.\s*(?:connect|request)\s*\(|navigator\s*\.\s*sendBeacon\s*\(|\bsendBeacon\s*\(|new\s+WebSocket\s*\(|\bWebSocket\s*\(|\bXMLHttpRequest\b|new\s+EventSource\s*\()".into(),
                pattern2: Some(r"(?:JSON\.stringify\s*\(\s*process\.env|Object\.(?:keys|entries|values)\s*\(\s*process\.env|process\.env\s*[\)\],}]|process\.env\.[A-Za-z_]*(?:SECRET|PASSWORD|CREDENTIAL)|AWS_SECRET|AWS_ACCESS|GITHUB_TOKEN|NPM_TOKEN|PRIVATE_KEY|SECRET_KEY|id_rsa|/\.ssh/|/\.npmrc|/\.aws/|/etc/passwd)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-004".into(),
                name: "Dynamic require".into(),
                description: "Dynamic module loading with string construction — can pull in attacker-controlled code".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"require\s*\(\s*(?:Buffer\s*\.\s*from|atob|decodeURIComponent|unescape|String\s*\.\s*fromCharCode|_0x[0-9a-fA-F])"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-004b".into(),
                name: "Dynamic import()".into(),
                description: "ESM dynamic import() with non-literal argument".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r#"import\s*\(\s*[^'"`\s]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-006".into(),
                name: "Encoded URL or IP".into(),
                description: "Obfuscated network address — hiding C2 or exfil destination".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"atob\s*\(\s*['\x22][A-Za-z0-9+/=]{20,}['\x22]\s*\)".into(),
                pattern2: Some(r"(?:fetch|https?|request|url|\.get|\.post|connect|socket)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into()],
            },
            Rule {
                id: "SC-007".into(),
                name: "File system read".into(),
                description: "Reading files — may access SSH keys, credentials, or configs".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r"(?:readFileSync|readFile|createReadStream|openSync|open\b)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "filesystem".into()],
            },
            Rule {
                id: "SC-008".into(),
                name: "VM execution context".into(),
                description: "vm.runInNewContext/runInThisContext — sandbox escape risk".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"vm\s*\.\s*(?:runInNewContext|runInThisContext|createContext|Script)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-009".into(),
                name: "WebAssembly instantiation".into(),
                description: "WebAssembly.instantiate — can run pre-compiled binary code".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"WebAssembly\s*\.\s*(?:instantiate|compile|instantiateStreaming)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-010".into(),
                name: "Prototype pollution".into(),
                description: "__proto__ or constructor.prototype access — prototype pollution vector".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r"(?:__proto__\s*[=\[]|constructor\s*\.\s*prototype\s*[=\.]|\[\s*['\x22`]__proto__['\x22`]\s*\]\s*=)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "prototype-pollution".into()],
            },
            Rule {
                id: "SC-011".into(),
                name: "Sensitive file path".into(),
                description: "Reference to sensitive file path — SSH keys, npmrc, credentials".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:\.ssh/id_rsa|\.ssh/id_ed25519|\.ssh/id_ecdsa|\.ssh/known_hosts|\.ssh/authorized_keys|/\.npmrc|/\.netrc|\.aws/credentials|\.aws/config|\.gnupg/|/etc/shadow|\.docker/config\.json|\.kube/config)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-012".into(),
                name: "DNS exfiltration".into(),
                description: "DNS resolution with sensitive data — DNS-based data exfiltration".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:dns\s*\.\s*(?:resolve|lookup)|dgram\s*\.\s*createSocket)\s*\(".into(),
                pattern2: Some(r"(?:process\.env|secret|token|password|credential|api[_-]?key|\.env\b|exfil)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-013".into(),
                name: "Crypto decipher".into(),
                description: "crypto.createDecipher — may decrypt embedded malicious payload (event-stream pattern)".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r"(?:createDecipher|createDecipheriv)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "crypto".into()],
            },
            Rule {
                id: "SC-014".into(),
                name: "Indirect eval via global".into(),
                description: "Accessing eval through globalThis/window/global — bypasses direct eval detection".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"(?:globalThis|window|global|self)\s*\[\s*['"`]eval['"`]\s*\]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            // ========== NEW: Expanded coverage ==========
            Rule {
                id: "SC-015".into(),
                name: "Shell command execution".into(),
                description: "execSync/spawn call with suspicious context — arbitrary command execution".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:execSync|execFileSync|spawnSync)\s*\(".into(),
                pattern2: Some(r"(?:base64\s+-d|base64\s+--decode|atob\s*\(|\bunescape\s*\(|fromCharCode|\\x[0-9a-fA-F]{2}|_0x[0-9a-fA-F]|eval\s*\(|Buffer\s*\.\s*from\s*\([^)]*['\x22](?:hex|base64)|/dev/tcp|\bnc\s+-e)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-015b".into(),
                name: "child_process.exec call".into(),
                description: "child_process.exec() — arbitrary command execution".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"child_process['\x22`\]]*\s*[\.\)]\s*exec\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-016".into(),
                name: "Raw network socket".into(),
                description: "net.Socket/createConnection — reverse shell or raw exfiltration channel".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:net\s*\.\s*(?:Socket|createConnection|connect)|new\s+net\s*\.\s*Socket|dgram\s*\.\s*createSocket)\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "network".into()],
            },
            Rule {
                id: "SC-017".into(),
                name: "process.mainModule access".into(),
                description: "process.mainModule.require — sandbox escape to load arbitrary modules".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"process\s*\.\s*mainModule\s*\.\s*require\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-018".into(),
                name: "OS fingerprinting".into(),
                description: "os module used for host reconnaissance — platform, user, hostname".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"os\s*\.\s*(?:platform|hostname|userInfo|homedir|networkInterfaces|cpus|release|type)\s*\(".into(),
                pattern2: Some(r"(?:fetch|https?|request|\.post|\.get|send|exfil|dns|socket|process\.env)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "recon".into()],
            },
            Rule {
                id: "SC-019".into(),
                name: "Node.js internal binding".into(),
                description: "process.binding — access dangerous internal modules".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"process\s*\.\s*(?:binding|_linkedBinding)\s*\(\s*['\x22](?:spawn_sync|fs|tcp_wrap|pipe_wrap|udp_wrap|tls_wrap|crypto|child_process)['\x22]".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-020".into(),
                name: "File system write".into(),
                description: "Writing files — payload drop, crontab modification, or key injection".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:writeFileSync|writeFile|appendFileSync|appendFile|createWriteStream)\s*\(".into(),
                pattern2: Some(r"(?:\.ssh|cron|\.bashrc|\.bash_profile|\.profile|authorized_keys|bin/|\.npmrc|payload|backdoor|\.env|passwd|shadow)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "filesystem".into()],
            },
            Rule {
                id: "SC-021".into(),
                name: "Shell command string".into(),
                description: "String containing shell download/execute commands — malware dropper pattern".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"['"`][^'"`]*(?:(?:curl|wget)\s[^'"`]*(?:\|\s*(?:sh|bash)|&&|\s-o\s|https?://)|powershell[^'"`]*\s-e|certutil[^'"`]*-urlcache|Invoke-WebRequest|\biex\s*\()[^'"`]*['"`]"#.into(),
                pattern2: Some(r"(?:child_process|\.exec\b|\bexec\b|\bspawn\b|execSync|spawnSync|\bFunction\b|\beval\b)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-022".into(),
                name: "child_process member access".into(),
                description: "Accessing exec/spawn methods from child_process — command execution setup".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r"require\s*\(\s*['\x22`]child_process['\x22`]\s*\)\s*\.\s*(?:exec|execSync|execFile|execFileSync|spawn|spawnSync|fork)\b".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            // ========== Evasion-resistant patterns ==========
            Rule {
                id: "OBF-008".into(),
                name: "Function constructor reference".into(),
                description: "Function constructor stored in variable/array — indirect dynamic code execution".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r"(?:[\[,=]\s*Function\s*[,\];\s]|\bFunction\b\s*(?:,|\]))".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-009".into(),
                name: "String fragment array".into(),
                description: "Array of many short string fragments — hiding URLs, code, or identifiers".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r#"\[\s*"[^"]{1,8}"\s*(?:,\s*"[^"]{1,8}"\s*){5,}\]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-010".into(),
                name: "Bracket-notation method call".into(),
                description: "obj[variable](...) — hiding method name via computed property access".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"\w+\[\s*\w+\s*\]\s*\([^)]*\)\s*\(".into(),
                pattern2: Some(r"(?:Function|eval|require|concat|exec|child_process)".into()),
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            // ========== HIGH-CONFIDENCE COMPOSITE SIGNATURES ==========
            // Decode-then-execute is the single most reliable malware signature.
            Rule {
                id: "OBF-011".into(),
                name: "eval of decoded payload".into(),
                description: "eval() wrapping a decoder (atob/Buffer.from/fromCharCode) or obfuscated identifier — decode-then-execute".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"eval\s*\(\s*(?:atob|unescape|decodeURIComponent|Buffer\s*\.\s*from|String\s*\.\s*fromCharCode|_0x[0-9a-fA-F]+)\b".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-012".into(),
                name: "Function constructor of decoded payload".into(),
                description: "Function() wrapping a decoder — dynamic execution of decoded code".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:new\s+Function|\bFunction)\s*\(\s*(?:atob|unescape|decodeURIComponent|Buffer\s*\.\s*from|String\s*\.\s*fromCharCode|_0x[0-9a-fA-F]+)\b".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-013".into(),
                name: "Function constructor with code string".into(),
                description: "new Function(\"...\") whose body references process/require/eval — runtime-built code".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r#"new\s+Function\s*\(\s*['"\x60][^'"\x60]*(?:return\s|process\b|require\b|eval\b|child_process|global(?:This)?\b)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-014".into(),
                name: "Hex identifier obfuscation".into(),
                description: "Multiple _0x-style hex identifiers — hallmark of obfuscator.io output".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"_0x[0-9a-fA-F]{4,}\b[\s\S]{0,400}?_0x[0-9a-fA-F]{4,}\b".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "structure".into()],
            },
            Rule {
                id: "SC-010b".into(),
                name: "Prototype pollution write".into(),
                description: "Computed write to [\"__proto__\"] — deliberate prototype pollution gadget".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"\[\s*['"\x60]__proto__['"\x60]\s*\](?:\s*\[[^\]]*\])?\s*="#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "prototype-pollution".into()],
            },
            Rule {
                id: "SC-023".into(),
                name: "Reverse shell pattern".into(),
                description: "Reverse-shell primitives (/dev/tcp, bash -i, nc -e, /bin/sh spawn, 0>&1) — remote shell".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"(?:/dev/tcp/|bash\s+-i\b|sh\s+-i\b|\bnc\s+-e\b|\bncat\s+-e\b|0>&1|>&\s*/dev/tcp|mkfifo\s)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into(), "c2".into()],
            },
            Rule {
                id: "SC-024".into(),
                name: "Decrypt-then-execute".into(),
                description: "crypto decipher feeding eval/Function/exec — encrypted payload execution (event-stream pattern)".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"createDecipher(?:iv)?\s*\(".into(),
                pattern2: Some(r"(?:eval\s*\(|new\s+Function|\bFunction\s*\(|child_process|\.exec\s*\(|spawn\s*\()".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "crypto".into(), "execution".into()],
            },
            Rule {
                id: "SC-025".into(),
                name: "WebAssembly from decoded bytes".into(),
                description: "WebAssembly.instantiate/compile fed decoded bytes — running a hidden binary payload".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"WebAssembly\s*\.\s*(?:instantiate|compile)(?:Streaming)?\s*\(".into(),
                pattern2: Some(r#"(?:Buffer\s*\.\s*from|atob|fromCharCode|['"\x60]base64['"\x60]|['"\x60]hex['"\x60])"#.into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-026".into(),
                name: "Exfiltration/C2 infrastructure".into(),
                description: "Reference to a known exfiltration/canary/C2 service domain".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"(?:webhook\.site|requestbin\.(?:com|net)|requestrepo\.com|pipedream\.net|\.oast\.(?:fun|site|live|pro|me|online)|interactsh|oastify\.com|burpcollaborator\.net|\.ngrok(?:-free)?\.(?:io|app|dev)|dnslog\.cn|canarytokens|\.mockbin\.io|\.beeceptor\.com)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-027".into(),
                name: "Connect to hardcoded IP".into(),
                description: "Outbound socket to a hardcoded IP address combined with data send — exfil or reverse channel".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"(?:createConnection|connect|Socket)\s*\(\s*\d{1,5}\s*,\s*['"\x60]\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}['"\x60]"#.into(),
                pattern2: Some(r"(?:process\.env|JSON\.stringify\s*\(\s*process|spawn\s*\(|\.exec\s*\(|/bin/(?:sh|bash))".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into(), "c2".into()],
            },
            Rule {
                id: "SC-028".into(),
                name: "Browser credential theft".into(),
                description: "Access to browser credential/cookie stores — token/cookie/password stealer".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"(?:Login Data|Local Storage[\\/]+leveldb|Cookies\.sqlite|cookies\.sqlite|key4\.db|logins\.json|signons\.sqlite|Local State|[\\/]Cookies\b|webappsstore\.sqlite)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-029".into(),
                name: "constructor.constructor escape".into(),
                description: "Reaching the Function constructor via .constructor.constructor — sandbox escape gadget".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"(?:\.\s*constructor|\[\s*['"\x60]constructor['"\x60]\s*\])\s*(?:\.\s*constructor|\[\s*['"\x60]constructor['"\x60]\s*\])\s*\("#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            // ========== PORTED FROM GUARDDOG (DataDog/guarddog) ==========
            // JS/npm source-code rules adapted from GuardDog's YARA rule set to
            // Vigil's regex + local-correlation model. Correlated rules require a
            // second signal within CORRELATION_WINDOW to keep false positives off
            // the benign corpus (bare clipboard/exec/os APIs are common in tools).
            Rule {
                id: "GD-001".into(),
                name: "Clipboard hijack (crypto clipper)".into(),
                description: "Clipboard read/write near a wallet address or network send — crypto-clipper that swaps copied addresses".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r#"(?:clipboardy\s*\.\s*(?:write|writeSync|read|readSync)|clipboard\s*\.\s*(?:readText|writeText)\s*\(|require\s*\(\s*['"]clipboardy['"]\s*\))"#.into(),
                pattern2: Some(r#"(?:0x[a-fA-F0-9]{40}|\bbc1[a-z0-9]{20,}|\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b|fetch\s*\(|\baxios\b|\.post\s*\(|https?://)"#.into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "GD-002".into(),
                name: "Keylogging module".into(),
                description: "Global keyboard-hook library (iohook, keypress, node-global-key-listener) — input/keystroke capture".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"(?:require\s*\(\s*['"](?:iohook|keypress|node-global-key-listener|node-key-sender)['"]\s*\)|\biohook\s*\.\s*start\s*\(|\bGlobalKeyboardListener\b)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "GD-003".into(),
                name: "Cryptominer reference".into(),
                description: "Reference to mining software, a mining pool, or the stratum protocol — cryptojacking payload".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?i)(?:\bxmrig\b|\bcgminer\b|\bbfgminer\b|\bcpuminer\b|\bccminer\b|\bethminer\b|stratum\+(?:tcp|ssl)://|\bsupportxmr\.com\b|\bminexmr\.com\b|\bnanopool\.org\b)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "GD-004".into(),
                name: "Self-propagating publish (worm)".into(),
                description: "Rewrites a package manifest and shells a registry publish — worm that clones and republishes itself".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"(?:writeFile(?:Sync)?|writeJson(?:Sync)?|outputJson(?:Sync)?)\s*\(\s*['"`][^'"`]*package(?:-lock)?\.json"#.into(),
                pattern2: Some(r#"['"`]\s*(?:npm|yarn|pnpm)\s+publish\b"#.into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "GD-005".into(),
                name: "Trojan-source / homoglyph unicode".into(),
                description: "Bidirectional override, zero-width, or Cyrillic/Greek homoglyph chars adjacent to ASCII — source-hiding obfuscation".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:[\x{202A}-\x{202E}\x{2066}-\x{2069}]|[A-Za-z][\x{200B}-\x{200D}\x{2060}\x{FEFF}][A-Za-z]|[A-Za-z][\p{Cyrillic}\p{Greek}]|[\p{Cyrillic}\p{Greek}][A-Za-z])".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "GD-006".into(),
                name: "Silent detached process spawn".into(),
                description: "detached:true combined with stdio 'ignore' / windowsHide — a spawned process deliberately hidden from view".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r#"["']?detached["']?\s*:\s*true"#.into(),
                pattern2: Some(r#"(?:["']?stdio["']?\s*:\s*(?:\[\s*)?["']ignore|["']?windowsHide["']?\s*:\s*true)"#.into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "GD-007".into(),
                name: "Console suppression with obfuscation".into(),
                description: "Overriding console.log/warn/error with a no-op alongside encoded code — silencing errors while running a hidden payload".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"console\s*\.\s*(?:log|warn|error)\s*=\s*function\s*\(\s*\)".into(),
                pattern2: Some(r"(?:fromCharCode|fromCodePoint|\[\s*0x[0-9a-fA-F]+\s*,\s*0x[0-9a-fA-F]+)".into()),
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "GD-008".into(),
                name: "PowerShell encoded command / cradle".into(),
                description: "PowerShell -EncodedCommand, hidden window, or Net.WebClient download cradle — Windows download-and-execute".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?i)(?:powershell[^'\x22`\n]{0,80}-enc(?:odedcommand)?\s+[A-Za-z0-9+/=]{20,}|-WindowStyle\s+Hidden|IEX\s*\(\s*New-Object\s+Net\.WebClient|New-Object\s+Net\.WebClient\s*\)\s*\.\s*Download(?:String|File)\s*\()".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "GD-009".into(),
                name: "LOLBAS network tool in command".into(),
                description: "certutil / bitsadmin / socat / Invoke-WebRequest inside a string driven by a process-spawn call — living-off-the-land download".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"['"`][^'"`]*(?:\bcertutil\b|\bbitsadmin\b|\bsocat\b|Invoke-WebRequest|Invoke-RestMethod)[^'"`]*['"`]"#.into(),
                pattern2: Some(r"(?:child_process|\bexecSync\b|\bspawnSync\b|\bexecFile\b|\bexec\b|\bspawn\b)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "GD-010".into(),
                name: "Host/network enumeration".into(),
                description: "Process/network enumeration module (ps-list, find-process, os.networkInterfaces) combined with a network or env-read sink — recon before exfiltration".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r#"(?:require\s*\(\s*['"](?:ps-list|find-process|process-list|network-list)['"]\s*\)|os\s*\.\s*networkInterfaces\s*\(\s*\))"#.into(),
                pattern2: Some(r"(?:fetch\s*\(|\baxios\b|https?[.:]|\.post\s*\(|socket|process\.env|exfil|dns\s*\.)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "recon".into()],
            },
            Rule {
                id: "GD-011".into(),
                name: "Autostart persistence".into(),
                description: "Writing to a shell rc, XDG autostart, /etc/init.d, macOS LaunchAgents, or the Windows Run registry key — boot persistence".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"(?:(?:writeFile|appendFile)(?:Sync)?\s*\([^;\n]{0,120}?['"`][^'"`]*\.(?:bashrc|zshrc|bash_profile)\b|['"`][^'"`]*\.config/autostart/|['"`][^'"`]*/etc/(?:init\.d|profile\.d|rc\.local)|['"`][^'"`]*/Library/Launch(?:Agents|Daemons)/|CurrentVersion\\{1,2}Run(?:Once)?\b)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "filesystem".into()],
            },
            // ========== EVASION HARDENING ==========
            // Close indirection/aliasing and modern-channel gaps found by
            // red-teaming the ruleset (probes that returned PASS but were
            // malicious in intent). Kept low-FP against the benign + real corpus.
            Rule {
                id: "OBF-015".into(),
                name: "eval/Function of computed value".into(),
                description: "eval() or Function() applied to a function-call result — decoder aliasing that hides the classic eval(atob(...)) signature".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:eval|new\s+Function|\bFunction)\s*\(\s*[A-Za-z_$][\w$]*\s*\(".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-016".into(),
                name: "Dangerous builtin referenced as value".into(),
                description: "eval/atob/require bound to a variable or passed as an argument instead of called directly — aliasing to dodge name-based rules".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"(?:=|[(,])\s*(?:eval|atob|require)(?:[^\w(.]|$)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "OBF-017".into(),
                name: "Require of indexed array literal".into(),
                description: "require([...])[i] — module name hidden inside an indexed array literal to evade string-literal matching".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"require\s*\(\s*\[[^\]]*\]\s*\[".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            Rule {
                id: "SC-004c".into(),
                name: "Dynamic require via template literal".into(),
                description: "require(`...${expr}...`) — module path assembled from a template with interpolation, potentially attacker-controlled".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r"require\s*\(\s*`[^`]*\$\{".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-030".into(),
                name: "DNS-over-HTTPS exfiltration".into(),
                description: "Request to a DNS-over-HTTPS resolver carrying secret/env data — covert DNS exfiltration that bypasses ordinary network sinks".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:dns\.google|cloudflare-dns\.com|dns\.quad9\.net|/dns-query\b|/resolve\?name=)".into(),
                pattern2: Some(r"(?:process\.env|\bsecret\b|\btoken\b|password|credential|api[_-]?key|\.(?:evil|attacker|exfil))".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-031".into(),
                name: "Loop-reconstructed string into sink".into(),
                description: "A loop assembling characters via fromCharCode feeding require/exec/eval — runtime string rebuild that the deobfuscator does not fold".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"for\s*\([^)]*\)\s*\{[\s\S]{0,150}?(?:String\.)?fromCharCode".into(),
                pattern2: Some(r"(?:require|eval|\bexec|\bspawn|\bFunction)\s*\(".into()),
                threshold: None,
                tags: vec!["obfuscation".into(), "execution".into()],
            },
            // ========== DECODER GAPS ==========
            // Decoder primitives the classic eval(atob(...)) signatures miss:
            // %-encoding, XOR loops, and fromCodePoint all rebuild a payload
            // without touching atob/Buffer.from.
            Rule {
                id: "OBF-018".into(),
                name: "Percent-encoded payload decode".into(),
                description: "unescape/decodeURIComponent of a long %XX-encoded blob — payload hidden as URL-encoding".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r#"(?:unescape|decodeURIComponent)\s*\(\s*['"](?:%[0-9a-fA-F]{2}){8,}['"]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-019".into(),
                name: "XOR char-code decryption".into(),
                description: "charCodeAt() XORed with a key feeding a decoder/sink — classic single-byte-XOR payload decryption loop".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"\w+\.charCodeAt\s*\([^)]*\)\s*\^\s*\w".into(),
                pattern2: Some(r"(?:fromCharCode|eval\s*\(|Function\s*\()".into()),
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-020".into(),
                name: "fromCodePoint decode".into(),
                description: "String.fromCodePoint with multiple numeric args — fromCharCode variant used to dodge signature matching".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"String\s*\.\s*fromCodePoint\s*\(\s*\d+\s*(?:,\s*\d+\s*)+\)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "encoding".into()],
            },
            Rule {
                id: "OBF-021".into(),
                name: "JSFuck-style minimal alphabet".into(),
                description: "Long run using only []()!+ characters — JSFuck/jsfuck-alphabet obfuscation executing code without letters".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"[\[\]()!+]{60,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["obfuscation".into(), "structure".into()],
            },
            // ========== ROUND 2: SUPPLY-CHAIN GAPS ==========
            // Evasion + C2/persistence patterns from recent npm malware waves
            // (token stealer campaigns, TeamPCP-style droppers, Shai-Hulud).
            Rule {
                id: "SC-032".into(),
                name: "node:-prefixed dangerous module".into(),
                description: "require/import of node:child_process or node:vm — the node: prefix dodges rules written for the bare module name".into(),
                severity: Severity::Low,
                kind: RuleKind::Regex,
                pattern: r#"(?:require\s*\(\s*|import\s+[^'"]*?\sfrom\s+)['"]node:(?:child_process|vm|worker_threads|cluster)['"]"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-033".into(),
                name: "Hardcoded Telegram Bot token".into(),
                description: "Full api.telegram.org/bot<id>:<token> URL — the package ships a working bot credential, i.e. a fixed Telegram C2 channel. Legit bot code takes tokens from config, never hardcodes them".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"api\.telegram\.org/bot\d{5,}:[A-Za-z0-9_-]{20,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-034".into(),
                name: "Hardcoded Discord webhook".into(),
                description: "Full discord.com/api/webhooks/<id>/<token> URL — the embedded token is itself the credential: a fixed attacker exfil channel. Legit Discord libraries never ship webhook secrets".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r"discord(?:app)?\.com/api/webhooks/\d{8,}/[A-Za-z0-9_-]{20,}".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-035".into(),
                name: "Raw IP address request".into(),
                description: "HTTP(S) URL with a hardcoded IP instead of a hostname, near exec or secret access — droppers skip DNS to dodge domain blocklists".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"https?://\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}".into(),
                pattern2: Some(r"(?:process\.env|readFileSync|exec|spawn|\.ssh|password|token|secret|homedir)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into()],
            },
            Rule {
                id: "SC-036".into(),
                name: "crontab/scheduled-task persistence".into(),
                description: "crontab/schtasks/systemctl-enable driven by a process spawn — boot persistence installed by the package".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"\b(?:crontab|schtasks|systemctl\s+enable)\b".into(),
                pattern2: Some(r"(?:child_process|execSync|spawnSync|\bexec\b|\bspawn\b)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "filesystem".into()],
            },
            Rule {
                id: "SC-037".into(),
                name: "Temp-directory dropper".into(),
                description: "os.tmpdir() combined with an exec/chmod/decode step — drop a payload to a world-writable temp dir and run it".into(),
                severity: Severity::Medium,
                kind: RuleKind::Regex,
                pattern: r"os\.tmpdir\s*\(\s*\)".into(),
                pattern2: Some(r"(?:execSync|spawnSync|execFileSync|chmod\s*\+?x?|\.exec\s*\(|Buffer\.from\s*\([^)]*['\x22]base64)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "execution".into()],
            },
            Rule {
                id: "SC-038".into(),
                name: "Hardcoded chat webhook (Slack/Teams/Google Chat)".into(),
                description: "Credential-bearing webhook URL for Slack (T../B../token path), Teams (webhookb2 path), Google Chat (?key=) or Guilded — a hardcoded exfil channel; legit integrations read webhook URLs from config".into(),
                severity: Severity::Critical,
                kind: RuleKind::Regex,
                pattern: r#"(?:hooks\.slack\.com/services/T[A-Z0-9]{6,}/B[A-Z0-9]{6,}/[A-Za-z0-9]{15,}|\.webhook\.office\.com/webhookb2/|chat\.googleapis\.com/v1/spaces/[^\s'"]+/messages\?key=|media\.guilded\.gg/webhooks/[\w-]+/[\w-]+)"#.into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "c2".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-039".into(),
                name: "Hand-rolled multipart file upload".into(),
                description: "Manually concatenated multipart/form-data body (Content-Disposition header built by string) — hand-built HTTP upload of local files, the classic stealer exfil mechanism; legit code uses the FormData API or the form-data package".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r"(?:Content-Disposition:\s*form-data|multipart/form-data;\s*boundary=)".into(),
                pattern2: None,
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
            Rule {
                id: "SC-040".into(),
                name: "HTTP module require near secrets".into(),
                description: "require/import of http, https, http2 or undici near a strong secret signal — catches aliased request calls (const h = require('https'); h.request(...)) that literal-call rules miss".into(),
                severity: Severity::High,
                kind: RuleKind::Regex,
                pattern: r#"(?:require\s*\(\s*|import\s+[^'"]*?\sfrom\s+)['"](?:node:)?(?:https?|http2|undici)['"]"#.into(),
                pattern2: Some(r"(?:JSON\.stringify\s*\(\s*process\.env|Object\.(?:keys|entries|values)\s*\(\s*process\.env|process\.env\s*[\)\],}]|process\.env\.[A-Za-z_]*(?:SECRET|PASSWORD|CREDENTIAL)|AWS_SECRET|AWS_ACCESS|GITHUB_TOKEN|NPM_TOKEN|PRIVATE_KEY|SECRET_KEY|id_rsa|/\.ssh/|/\.npmrc|/\.aws/|/etc/passwd)".into()),
                threshold: None,
                tags: vec!["supply-chain".into(), "exfiltration".into()],
            },
        ],
    }
}
